### PR TITLE
Enhance PanAndZoom with touch support for pinch zoom and single-finger pan

### PR DESCRIPTION
**Pull request by sago35**
#20

This PR adds touch support.
It's a minimal implementation, but it allows for comfortable use of KiCanvas from platforms like Android.

See https://twitter.com/i/status/1739613481052307890

### CODE REVIEW

**Comment by sago35** [comment]
I have confirmed that touch support works in the following environments:

- Android
- iPhone
- Windows 11 + TouchScreen

**Comment by theacodes** [comment]
Looks like lint is failing, do you mind giving that a look?

**Comment by sago35** [comment]
I have fixed the issue. However, it seems that the following warning still exists. I have not corrected this warning, but I can do so if needed.

```
$ npm run lint:prettier

> kicanvas@0.0.0 lint:prettier
> prettier . --check

Checking formatting...
[warn] src/kicanvas/elements/kc-board/properties-panel.ts
[warn] src/kicanvas/elements/kc-schematic/properties-panel.ts
[warn] Code style issues found in 2 files. Run Prettier to fix.
```

**Comment by sago35** [comment]
@theacodes 
Can you run the CI first?

**Comment by theacodes** [comment]
Looks good. Any thing else before I merge? :)

**Comment by sago35** [comment]
@theacodes 
It's fine to merge as it is. Thank you for checking.

**Pull request merged**
